---
- name: Configure Database servers
  hosts: rhel
  become: true

  vars:
    pgadmin_container:
      name: pgadmin
      image: docker.io/dpage/pgadmin4
      state: started
      volumes:
        - /etc/localtime:/etc/localtime:ro
      env:
        PGADMIN_DEFAULT_EMAIL: student@example.com
        PGADMIN_DEFAULT_PASSWORD: learn_ansible
      ports:
        - 8083:80
      log_options:
        max_size: 10

  tasks:
        # TASK 1
        # # 1a. Uncomment task description below and generate a single task suggestion.
        # #     Note - The suggestion included Ansible best practices by using Fully Qualified Collection name (FQCN).
        # #     Note - The suggestion used natural language prompt and inferred the correct installation package.

    # - name: Install postgresql server package

        # TASK 2
        # # 2a. Press "ENTER" at the end of the multi-task prompt line.
        # #     Task 1 note - The suggestion used simple request and provided the correct terminal command to use.
        # #                   The suggestion is idempotent. An Ansible best-practice
        # #     Task 2 note - The suggestion used the Playbook context to know it should start the "postgresql service".
        # #     Task 3 note - The suggestion used the correct default PostgreSQL TCP port (5432).

    # Do initial postgresql config & start the service & allow the traffic through the firewall

        # TASK 3
        # # 1a. Uncomment task description below and generate a single task suggestion.
        # #     Note - The suggestion integrated the "pgadmin_container" var as requested in the prompt

    # - name: Create podman container using pgadmin_container var
