---
- name: Install and configure Cockpit
  hosts: rhel
  become: true

  tasks:
        # TASK 1
        # # 1a. Uncomment task description below and generate a single task suggestion.
        # #     Note - The suggestion included Ansible best practices by using Fully Qualified Collection name (FQCN).
        # #     Note - The suggestion used the Certified Content Collection specified in the prompt.

    - name: Install cockpit using redhat.rhel_system_roles collection
      ansible.builtin.include_role:
        name: redhat.rhel_system_roles.cockpit

        # TASK 2
        # # 2a. Uncomment task description below and generate a task suggestion.
        # #     Note - Ansible Lightspeed used "ansible.builtin.template" module based on the ".j2" file extension.
        # #     Note - The suggestion set the file permissions ("0644"), owner, and group based on Ansible best practices.

    - name: Copy cockpit.conf.j2 to /etc/cockpit
      ansible.builtin.template:
        src: cockpit.conf.j2
        dest: /etc/cockpit/cockpit.conf
        owner: root
        group: root
        mode: '0644'


        # TASK 3
        # # 3a. Press "ENTER" at the end of the multi-task prompt line
        # #     First task note - Ansible Lightspeed used the generic "Restart and enable service" prompt
        # #            and full Playbook context to infer the recommendation should restart the "cockpit" service.
        # #     Second task note -Ansible Lightspeed used the generic language prompt and Playbook context
        # #            and used the correct default Cockpit service port (9090) in the suggestion.

    # Restart and enable service & wait 15 seconds for it to be available
    - name: Restart and enable service
      ansible.builtin.service:
        name: cockpit.socket
        state: restarted
        enabled: true

    - name: Wait 15 seconds for it to be available
      ansible.builtin.wait_for:
        port: 9090
        delay: 15
